### PR TITLE
Update Docker images/README

### PR DESCRIPTION
**Pull request by koverholt**
* Update to Debian 8.5 base image
* Add Jupyter notebook installation and startup
* Remove unused libraries/commands
* Update description and usage in README

@mutirri, can you review these changes? We can iterate on this image first, then I can update the other images (anaconda, anaconda3, miniconda). Note that the updated base image and removed libraries were based on the results of the [Docker security scan](https://docs.docker.com/docker-cloud/builds/image-scan/).

### CODE REVIEW

**Comment by mutirri** [comment]
@koverholt sure, I will do this at the end of this week or early in next one.

**Comment by mutirri** [comment]
Just after first glance I can say that we have probably some misunderstanding here.
As far as I know people use these images as minimal, stable and **raw** base for many - quite often different - purposes.
For example they use it as a basis of their automatic environments.

1. The base 'init' process.

  You removed support for `tini`. Please be aware of (https://github.com/ContinuumIO/docker-images/pull/18):

  - http://blog.dscpl.com.au/2015/12/issues-with-running-as-pid-1-in-docker.html

  - https://blog.phusion.nl/2015/01/20/docker-and-the-pid-1-zombie-reaping-problem/

  - https://stackoverflow.com/questions/37374310/how-critical-is-dumb-init-for-docker

2.  Removing some dependencies.

  a) In the past many people ask for tools like `git` to be available out of the box.
  b) There were some requests to add by default some missing libraries, check  https://github.com/ContinuumIO/docker-images/pull/9.

3. Changing `default` behavior of `ENTRYPOINT`.


Probably there were other assumptions of these images as well.
Don't get me wrong, I'm just worried a little bit of breaking the old compatibility and expectations.
That's all.

**Comment by koverholt** [comment]
Thanks for the feedback, @mutirri. I reverted my changes to get back to the base image that you had. I think the main question is if this image will be used for Anaconda builds, or Anaconda end-users. We also have some build images in this repo for the former case.

1. I've bumped the version of debian to 8.5, this reduces the number of security issues from the Docker scanning service from 26 to 10.

2. Do we need `git`, `mercurial`, and `subversion` in this image? Would those be better suited in the build images?

3. Do we still need all of these libraries? `libglib2.0-0 libxext6 libsm6 libxrender1`

4. To avoid increasing the size of this image, I've included a command in the README to launch a Jupyter Notebook server rather than including it in the image.

**Comment by koverholt** [comment]
Disregard items 3 and 4 in my previous message, I now see the context in which those libraries were added in commits 3bb4561 and 532637a.

**Comment by mutirri** [comment]
Hi @koverholt 

OK, I had to apply small fix (https://github.com/ContinuumIO/docker-images/pull/32/commits/4830ca9c1d3350baa67b38132f7953615164666e) to your changes.
Generally this looks good for me.
After fixing I was able to build all images locally without any problems.
Green light from me.

**Comment by mutirri** [comment]
All images are now built and ready to use:
a) https://hub.docker.com/r/continuumio/anaconda/tags/ (4.0.0p0 + latest)
b) https://hub.docker.com/r/continuumio/anaconda3/tags/ (4.0.0p0 + latest)
c) https://hub.docker.com/r/continuumio/miniconda3/tags/ (4.0.5p0 + latest)
d) https://hub.docker.com/r/continuumio/miniconda/tags/ (4.0.5p0 + latest)

**Comment by koverholt** [comment]
Thanks @mutirri!

**Pull request merged**
