### PR TITLE
Kkwiek/images upgrade

### PR DESCRIPTION
**Pull request by mutirri**

### CODE REVIEW

**Comment by mutirri** [comment]
Hi @tswicegood,
Could you look on this and merge?
After that I will manually trigger the building process to create new images.

**Comment by tswicegood** [comment]
:+1:

**Comment by tswicegood** [comment]
@mutirri are these up on Docker Hub?

**Comment by pelson** [comment]
> @mutirri are these up on Docker Hub?

You could CI that... https://docs.docker.com/docker-hub/builds/

**Comment by mutirri** [comment]
> @mutirri are these up on Docker Hub?

@tswicegood  Yes.
I had to change location of `Anaconda3` installer file because it seems that separate directory is no longer in use. The change was pushed directly to master.
Of course I was able to build `Anaconda3` locally by using this improved `Dockerfile`.

Docker hub has some problems when too many builds are triggered from one repository in the same time - builds hangs from time to time.
I'm going to restart this build after a while.

> You could CI that... https://docs.docker.com/docker-hub/builds/

@pelson we know that and images were prepared in this way.
However there was a problem with `webhook` and permissions on `docker-images` repository - automatic trigger didn't work.
Right now automated builds are working just fine - images are built properly.

Feel free to use those images.

**Pull request merged**
