### PR TITLE
Major Refactoring 

### PR DESCRIPTION
**Pull request by tyler-thetyrant**

### CODE REVIEW

**Comment by jontonsoup** [comment]
@tyler-thetyrant does this upgrade to python 3.6?

**Comment by tyler-thetyrant** [comment]
@jontonsoup As we install Continuum's python when installing conda, all default python on miniconda3 docker images should be Python 3.6.0

**Comment by jontonsoup** [comment]
Do you mean on this PR or on master? 

I checked on master:latest and it was 3.5. That said, I could be seeing a caching issue.

**Comment by tyler-thetyrant** [comment]
@jontonsoup  I just checked master, and it shows: 
`Python 3.6.0 |Continuum Analytics, Inc.| (default, Dec 23 2016, 12:22:00) `

I might be a caching issue on your side, but I'm not sure.

**Comment by jontonsoup** [comment]
@tyler-thetyrant yup! my cache busted on its own in between this and my last comment. 

Thanks!

**Comment by dbast** [comment]
Thx. Closing as outdated.

**Pull request closed without merging**
